# Generated by Django 4.2.1 on 2023-05-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Partner", models.CharField(max_length=255)),
                ("Img", models.ImageField(blank=True, upload_to="logoPartner/")),
            ],
        ),
        migrations.RemoveField(model_name="projet", name="clientP",),
        migrations.AddField(
            model_name="projet",
            name="clients",
            field=models.ManyToManyField(related_name="projets", to="ArtyProd.client"),
        ),
    ]
