# Generated by Django 4.2.1 on 2023-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0002_partner_remove_projet_clientp_projet_clients"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="address",),
        migrations.RemoveField(model_name="client", name="phone_number",),
        migrations.AddField(
            model_name="client",
            name="adresse",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="nom",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="telephone",
            field=models.CharField(default="", max_length=255),
        ),
    ]
