# Generated by Django 4.2.1 on 2023-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0003_remove_client_address_remove_client_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="statut",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
