# Generated by Django 4.2.1 on 2023-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0004_personnel_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="statut",
            field=models.BooleanField(default=False),
        ),
    ]
