# Generated by Django 4.2.1 on 2023-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0006_remove_personnel_statut"),
    ]

    operations = [
        migrations.RemoveField(model_name="projet", name="Img",),
        migrations.AddField(
            model_name="projet",
            name="Details",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
