# Generated by Django 4.2.1 on 2023-05-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0007_remove_projet_img_projet_details"),
    ]

    operations = [
        migrations.RemoveField(model_name="projet", name="clients",),
        migrations.DeleteModel(name="Detail",),
        migrations.AddField(
            model_name="projet",
            name="clients",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ArtyProd.client",
            ),
        ),
    ]
