# Generated by Django 4.2.1 on 2023-05-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0008_remove_projet_clients_delete_detail_projet_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalerieProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.FileField(blank=True, null=True, upload_to="media/")),
                ("legende", models.CharField(blank=True, max_length=255)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ArtyProd.projet",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Partner",),
    ]
