# Generated by Django 4.2.1 on 2023-05-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0010_tache"),
    ]

    operations = [
        migrations.RemoveField(model_name="equipe", name="Img",),
    ]
