# Generated by Django 4.2.1 on 2023-05-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0012_remove_tache_titre"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_projet", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("statut", models.CharField(default="en_attente", max_length=20)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ArtyProd.client",
                    ),
                ),
            ],
        ),
    ]
