# Generated by Django 4.2.1 on 2023-05-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0013_demandeprojet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeprojet",
            name="statut",
            field=models.CharField(
                choices=[
                    ("En_attente", "En_attente"),
                    ("Acceptée", "Acceptée"),
                    ("Rejetée", "Rejetée"),
                ],
                default="En_attente",
                max_length=50,
            ),
        ),
    ]
