# Generated by Django 4.2.1 on 2023-05-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0003_alter_comment_user"),
        ("ArtyProd", "0014_alter_demandeprojet_statut"),
    ]

    operations = []
