# Generated by Django 4.2.1 on 2023-05-23 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArtyProd", "0016_alter_comment_user_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projet", old_name="Details", new_name="details",
        ),
        migrations.AddField(
            model_name="projet",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.DeleteModel(name="Profile",),
    ]
